apiVersion: 1

datasources:
  - name: PostgreSQL-Parcial
    uid: pg-parcial
    type: grafana-postgresql-datasource
    access: proxy
    url: database:5432
    user: ${POSTGRES_USER}
    isDefault: true
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${POSTGRES_PASSWORD}